### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Add a div to contain car image to the HTML.
- [x]  Ensure the car is visible at the top left of the screen.
- [x]  Style car image to ensure it only occupies a fraction of the screen to ensure it has room to drive later.
- [x]  Style the car's environment.
- [x]  Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x]  Ensure car and page look nice and renders correctly again in a private browsing session. 
- [x]  Fix all errors.
