### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  Create a data model that includes which way the car is facing (north, south, east, west).
- [x]  Create `class` attributes associated with the direction the car is facing (north, south, east, west) and style appropriately.
- [x]  Listen for arrow `keydown` events on the `document` and: 
  - [x]  Update car's `data-direction` attribute to correct direction.
  - [x]  Update data model `direction` property.
- [x]  Verify that `direction` property is saved to local storage on page reload.
- [x]  Ensure that after refreshing the page, the car is facing the same direction as before refreshing.
- [x]  Clean up all unnecessary CSS styling.
- [x]  Test functionality and styling in private browsing tab.
- [x]  Fix all errors.
